import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

/** Every .ts source that must be loadable: src/** and scripts/**, excluding tests and this generator's own output. */
export function loadableFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) { walk(p); continue; }
      if (name.endsWith(".ts") && !name.endsWith(".d.ts")) out.push(relative(root, p));
    }
  };
  for (const top of ["src", "scripts"]) walk(join(root, top));
  return out.sort();
}

/** test/load/<path with / → __>.load.test.ts */
export const loadTestPathFor = (file: string) => `test/load/${file.replace(/\.ts$/, "").replace(/\//g, "__")}.load.test.ts`;

/** Entry-point scripts run on import (they call process.exit / hit the network); they are load-tested as a subprocess with a guard env instead. */
export const RUNS_ON_IMPORT = new Set([
  "scripts/load/generate.ts", "scripts/release/check.ts", "scripts/release/publish-needed.ts",
  "scripts/release/notes.ts", "scripts/coverage/gate.ts", "scripts/verify-generated-is-committed.ts",
]);

export function loadTestSource(file: string): string {
  const rel = JSON.stringify("../../" + file);
  const importPath = JSON.stringify("../../" + file.replace(/\.ts$/, ".js"));
  const name = JSON.stringify("loads: " + file);
  if (RUNS_ON_IMPORT.has(file)) {
    // Entry point: importing would RUN it. A transpile proves syntax; resolving
    // each relative import proves the file is wired to things that exist.
    return [
      `// GENERATED by scripts/load — do not edit. Proves ${file} parses and its imports resolve.`,
      'import { test, expect } from "bun:test";',
      `test(${name}, async () => {`,
      `  const here = new URL(${rel}, import.meta.url);`,
      '  const src = await Bun.file(here).text();',
      '  const t = new Bun.Transpiler({ loader: "ts" });',
      '  expect(() => t.transformSync(src)).not.toThrow();',
      '  for (const imp of t.scanImports(src)) {',
      '    if (!imp.path.startsWith(".")) continue;',
      '    const target = new URL(imp.path.replace(/[.]js$/, ".ts"), here);',
      '    expect(await Bun.file(target).exists(), "unresolved import " + imp.path).toBe(true);',
      '  }',
      '});',
      '',
    ].join("\n");
  }
  return [
    `// GENERATED by scripts/load — do not edit. Proves ${file} is loadable.`,
    'import { test, expect } from "bun:test";',
    `test(${name}, async () => {`,
    `  const mod = await import(${importPath});`,
    '  expect(mod).toBeDefined();',
    '});',
    '',
  ].join("\n");
}
