// GENERATED by scripts/load — do not edit. Proves scripts/release/facts.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/release/facts.ts", async () => {
  const mod = await import("../../scripts/release/facts.js");
  expect(mod).toBeDefined();
});
