// GENERATED by scripts/load — do not edit. Proves scripts/load/inventory.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/load/inventory.ts", async () => {
  const mod = await import("../../scripts/load/inventory.js");
  expect(mod).toBeDefined();
});
