// GENERATED by scripts/load — do not edit. Proves scripts/coverage/lcov.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/coverage/lcov.ts", async () => {
  const mod = await import("../../scripts/coverage/lcov.js");
  expect(mod).toBeDefined();
});
