// GENERATED by scripts/load — do not edit. Proves scripts/release/publish-needed.ts parses and its imports resolve.
import { test, expect } from "bun:test";
test("loads: scripts/release/publish-needed.ts", async () => {
  const here = new URL("../../scripts/release/publish-needed.ts", import.meta.url);
  const src = await Bun.file(here).text();
  const t = new Bun.Transpiler({ loader: "ts" });
  expect(() => t.transformSync(src)).not.toThrow();
  for (const imp of t.scanImports(src)) {
    if (!imp.path.startsWith(".")) continue;
    const target = new URL(imp.path.replace(/[.]js$/, ".ts"), here);
    expect(await Bun.file(target).exists(), "unresolved import " + imp.path).toBe(true);
  }
});
