// GENERATED by scripts/load — do not edit. Proves src/registry/registry.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/registry/registry.ts", async () => {
  const mod = await import("../../src/registry/registry.js");
  expect(mod).toBeDefined();
});
