// GENERATED by scripts/load — do not edit. Proves src/channel/sender.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/channel/sender.ts", async () => {
  const mod = await import("../../src/channel/sender.js");
  expect(mod).toBeDefined();
});
