// GENERATED by scripts/load — do not edit. Proves src/registry/history.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/registry/history.ts", async () => {
  const mod = await import("../../src/registry/history.js");
  expect(mod).toBeDefined();
});
