// GENERATED by scripts/load — do not edit. Proves src/channel/index.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/channel/index.ts", async () => {
  const mod = await import("../../src/channel/index.js");
  expect(mod).toBeDefined();
});
